### ISSUE TITLE
Question on accessing images in public/ folder.

### ISSUE THREAD

**Issue by CR1AT0RS** [MasterKale/django-cra-helper#18]
Hey,

What's the correct way of accessing images in public/ folder inside your cra app?

I am trying to access the image in a react component. 
I tried the <img src="/build/static/media/test.png" /> It didn't work.
@MasterKale

**Comment by MasterKale** [comment]
I'd say the "correct" solution to this scenario is to use [Django's static files system](https://docs.djangoproject.com/en/3.1/howto/static-files/). This library _does_ support [referencing images located **within the src/ folder**](https://github.com/MasterKale/django-cra-helper#referencing-react-static-files), but that's assuming the images end up in the **asset-manifest.json** file that `react-scripts build` outputs. Files in Create-React-App's **public/** folder don't end up in the manifest so **cra_helper** has no idea what's in there and thus it can't expose them for use in Django's templates.

If you're at the point that you're incorporating a Create-React-App into a Django project with this library, then I think it should be assumed that the Create-React-App project isn't going to be maintained as a standalone single-page application. It would be no problem, then, to relocate any images in CRA's **public/** folder to wherever it's appropriate in your Django project to be served via Django's static files mechanism.

Fortunately with Django serving these images _and_ hosting the React app, it would be simple to use Django-hosted images within the React app: you'd just need to reference them via a Django static asset URL instead of referencing them relative to Create-React-App **public/** folder.

**Comment by CR1AT0RS** [comment]
Sounds good! Yes, I did end up using Django static folder. Thank you :)!
