### ISSUE TITLE
Possibility to delete the build folder in production

### ISSUE THREAD

**Issue by vsobotka** [MasterKale/django-cra-helper#22]
Hi,
Thanks for this module. It really helps a lot.

We are currently having an issue in production where we need to lower the size of our production app. Is it possible for `cra_helper` to not require `reactjs/build/`in production? If I understand it correctly, it is there needed only until we call the `collectstatic`. After that, we should be able to delete it. Is that a right assumption?

**Comment by MasterKale** [comment]
I'm glad to hear someone is using this in production! I honestly haven't been sure this would be suitable for more than hobby projects so it's heartening to get feedback that this is a viable production solution 😍 

As to your question, I played around a little bit and unfortunately the current version of the library requires that **reactjs/build/asset-manifest.json** be present even after running `collectstatic`. Everything else in the **reactjs/build/** folder can be deleted, it's just **asset-manifest.json** that needs to remain.

...Which feels like a bug to me. Digging a bit deeper, since asset-manifest.json gets scooped up in the `collectstatic` command, this library's `CRAManifestFinder` can be updated to try and access the one in the **static/** folder if the one in **reactjs/build/** is missing, and _then_ fail. This would make it possible to completely remove the **build/** directory!

Let me see what I can do...

**Comment by MasterKale** [comment]
@vsobotka I just published `django-cra-helper==1.2.3` to PyPI that should allow you to completely remove your **reactjs/build/** directory provided you've run `collectstatic` and confirmed that **asset-manifest.json** exists in `STATIC_ROOT`. Give it a try and let me know what you think.

**Comment by vsobotka** [comment]
@MasterKale Hi, thanks for such a quick response and action! Taking the `STATIC_ROOT` into consideration makes a perfect sense and is the ideal solution. I am currently testing it in the staging environment and it looks it is working perfectly. Thanks a lot!

> I honestly haven't been sure this would be suitable for more than hobby projects so it's heartening to get feedback that this is a viable production solution 😍
I have no idea how else would I do that to be honest. We are using it for www.simcompanies.com roughly for about 9 months now and it has worked wonders. So really thank you for this amazing plugin!

**Comment by vsobotka** [comment]
@MasterKale Hi, thanks for such a quick response and action! Taking the `STATIC_ROOT` into consideration makes a perfect sense and is the ideal solution. I am currently testing it in the staging environment and it looks it is working perfectly. Thanks a lot!

> I honestly haven't been sure this would be suitable for more than hobby projects so it's heartening to get feedback that this is a viable production solution 😍

I have no idea how else would I do that to be honest. We are using it for www.simcompanies.com roughly for about 9 months now and it has worked wonders. So really thank you for this amazing plugin!
