### ISSUE TITLE
"The development server has disconnected"

### ISSUE THREAD

**Issue by cnorthwood** [MasterKale/django-cra-helper#6]
Hi,

Thanks so much for the library, it's exactly what I was looking for :) However, I am having an issue with hot reloading.

Following the recommended instructions and adding `re_path(r'^sockjs-node/(?P<path>.*)$', proxy_cra_requests),` is giving me an error in the console followed by "The development server has disconnected:

    WebSocket connection to 'ws://localhost:8000/sockjs-node' failed: Error during WebSocket handshake: Unexpected response code: 301

I've thought this may be due to the slash, so I varied it by making the slash optional in the regex, and now I get:

    webpackHotDevClient.js:60 WebSocket connection to 'ws://localhost:8000/sockjs-node' failed: Error during WebSocket handshake: 'Upgrade' header is missing

Am wondering if this is a me issue, a docs issue, or a version incompatibility issue, if anyone's using this library and come across this?

Thanks

**Comment by MasterKale** [comment]
Hmm, my initial thought is that Create-React-App has probably switched to Websockets from HTTP, causing Django to try redirecting from `ws://` to `http://` (hence the unexpected [HTTP 301](https://en.wikipedia.org/wiki/HTTP_301) response).

@cnorthwood Can you confirm which version of `react-scripts` your project is using? And if possible, can you go into your browser's Dev Tools' Network section and give me a screenshot of the Request and Response panels for that `ws://` request?

**Comment by cnorthwood** [comment]
I'm using react-scripts 3.4.0 (this is a new project).

Screenshot attrached:

![Screenshot 2020-03-02 at 13 46 05](https://user-images.githubusercontent.com/462992/75681797-35710e80-5c8c-11ea-8e0a-bed9ff78088d.png)

**Comment by MasterKale** [comment]
Thanks for linking that, I think your second "'Upgrade' header is missing" error response is the actual problem (which you already knew because you made the trailing slash optional to fix the 301 😛)

I poked around Create-React-App and its packages and I have an idea of what might be happening: it looks like in CRA v3.3 they update the hot reload dev server [to use native Websockets instead of the **sockjs-client** library they were using in v3.2 and earlier](https://github.com/facebook/create-react-app/pull/7988). I suspect this is part of what's causing this breakage.

I also noticed that the **django-proxy** view I'm using to proxy this connection is [stripping the `Upgrade` header](https://github.com/mjumbewu/django-proxy/blob/master/proxy/views.py#L51) when it proxies, which might explain the ultimate error message. This library says it's a "simple HTTP proxy" so perhaps it's no longer suitable for use in proxying `ws://` URLs...

Work is nuts so I won't be able to work on this right away, but I'll definitely find time to test it out with CRA v3.4 and find a fix 😄

**Comment by cnorthwood** [comment]
Thanks for looking into it :)

**Comment by MasterKale** [comment]
I think I've figured out how to fix this:

1. Create an **.env** file in the root of your Create-React-App folder with the following environment variable:
```
WDS_SOCKET_PORT=3000
```
2. Re-run `npm start`, then reload your Django view

The CRA liveserver should now connect to `ws://localhost:3000` and re-enable live-reloading even from within Django:

https://giant.gfycat.com/CourteousEdibleHyrax.webm
(A screen recording showing live reloading working in Django using react-scripts@3.4.0)

This means the following entry in **urls.py** is _no longer required for react-scripts@3.3.0 and up_:
```
re_path(r'^sockjs-node/?(?P<path>.*)$', proxy_cra_requests),
```

@cnorthwood If you can confirm this fixes the problem on your end then I'll just need to update the README accordingly!

**Comment by cnorthwood** [comment]
This works excellently! Thanks so much for doing the digging and getting a straightforward answer :)

**Comment by MasterKale** [comment]
I've addressed this issue with some updates to **README.md** (see PR #8) highlighting the ability to use the above **.env** trick with current versions of create-react-app!
